<a href="https://colab.research.google.com/github/rahul10-pu/Numpy-Practice/blob/master/in_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
lst = [5, 10, 0, 200] 
import numpy as np
arr = np.array(lst)
print(arr + 5)
# Output:
# [10, 15, 5, 205]

In [0]:
lst = [1, 2, 3, 'text', True, 3+2j] 
import numpy as np
arr = np.array(lst)
print(type(arr[0]),type(arr[4]), type(arr[5]))
# Output:
# <class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'>

In [0]:
lst = [56, 45, 12, 6]
import numpy as np
arr = np.array(lst)
print(arr.nbytes)
# Output:
# 16 

In [0]:
''' Creation of an array with step size 1.33 between 0 - 10 '''
print(np.arange(0, 10, 1.33, dtype = np.float64))
# [ 0.    1.33  2.66  3.99  5.32  6.65  7.98  9.31]
# arange() gives uncertain number of values based on steps
# Hence, we use linspace, which asks for total number of values 
''' Creation of an array with total 5 values between 0 - 160 '''
print(np.linspace(0, 160, 5, dtype = np.float64))
# [   0.   40.   80.  120.  160.] 
 

In [0]:
''' Method I: Using array and reshape to convert array into matrix '''
print(np.array([5,6,8,45,12,52]).reshape(2,3))
# [[ 5  6  8]
#  [45 12 52]]
''' Method II: Using matrix function '''
print(np.matrix([[1,2],
                [3,4]]))
# [[1 2]
#  [3 4]]
''' Method III: Using misc. functions '''
print(np.eye(3)) # Identity matrix
# [[ 1.  0.  0.]
#  [ 0.  1.  0.]
#  [ 0.  0.  1.]]
print( np.zeros( (4,3) ) )
# [[ 0.  0.  0.]
#  [ 0.  0.  0.]
#  [ 0.  0.  0.]
#  [ 0.  0.  0.]]
print(np.ones( (3,3), dtype = np.float64 ))
# [[ 1.  1.  1.]
#  [ 1.  1.  1.]
#  [ 1.  1.  1.]]

In [16]:
import numpy as np
arr1 = [25, 56, 12, 85, 34, 75]
arr2 = [42, 3, 86, 32, 856, 46]
np.asarray(arr1).shape
Narr=np.random.rand(np.asarray(arr1).shape[0])
arr1 = np.array(arr1,dtype = complex)
arr1_mat =np.array(arr1).reshape(2,3)
arr2_mat=np.array(arr2).reshape(2,3)
(np.square(arr1_mat)-np.square(arr2_mat))/(arr1_mat-arr2_mat)

array([[ 67.-0.j,  59.+0.j,  98.-0.j],
       [117.+0.j, 890.-0.j, 121.+0.j]])

In [18]:
import numpy as np

arr1 = np.ones(10)
print(arr1)
arr2 = np.arange(10, dtype = np.float64)
print(arr2)
arr3 = arr1 + arr2
print(arr3)
print(np.result_type(arr1))
print(np.result_type(arr3))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64
float64


we're given a literacy rate data sample of State X and State Y for two consecutive years measured quarterly on a scale of 0-10.

In [0]:

S_X = np.array([[2, 5, 6, 5],
               [4, 8, 6, 5]])
print(S_X)
# [[2 5 6 5]
#  [4 8 6 5]]
S_Y = np.array([[6, 7, 5, 9],
               [7, 5, 6, 4]])
print(S_Y)
# [[6 7 5 9]
#  [7 5 6 4]] 
###Quarterly difference between each state's literacy rate per year.
print(S_Y - S_X)
# [[ 4  2 -1  4]
#  [ 3 -3  0 -1]] 
#result1: we can state that for first quarter of first-year State Y has 4 times more literacy rate than State X and so on for other quarters.

###Quarters having a literacy rate less than 2.
''' Method 1 '''
print(S_X < 2)
# [[False False False False]
#  [False False False False]]
''' Method 2 '''
twos_mat = np.ones((2, 4)) * 2
print(np.less(S_Y, twos_mat))
# [[False False False False]
#  [False False False False]] 

######Quarters having a literacy rate with cumulative sum of more than or equal to 8 per year.
#https://i.stack.imgur.com/gj5ue.jpg
X_cumsum = np.cumsum(S_X, axis = 1)
# [[2 5 6 5]
#  [4 8 6 5]]
print(X_cumsum)
# [[ 2  7 13 18]
#  [ 4 12 18 23]]
print( X_cumsum >= 8)
# [[False False  True  True]
#  [False  True  True  True]]
Y_cumsum = np.cumsum(S_Y, axis = 1)
print(Y_cumsum)
# [[ 6 13 18 27]
#  [ 7 12 18 22]]
print( Y_cumsum >= 8)
# [[False  True  True  True]
#  [False  True  True  True]] 
########### Mean of each year's literacy rate of State X and mean of each quarterly's literacy rate of State Y.
print(np.mean(S_X, axis = 1))
# [ 4.5   5.75]
print(np.mean(S_Y, axis = 0))
# [ 6.5  6.   5.5  6.5]


In [35]:
#TODO:-Numpy Operation Exercise
np.diag([4,5,6],1)
arr = np.arange(11)
np.negative(arr[6:])
print(np.arange(0, 10, 5, dtype = np.int32))
print(np.linspace(0, 10, 5, dtype = np.float64))
print(np.linspace(0, 10, 5, dtype = np.int32))
print(np.arange(0, 10, 5, dtype = np.float64))

[0 5]
[ 0.   2.5  5.   7.5 10. ]
[ 0  2  5  7 10]
[0. 5.]
